[package]
name = "ucode-providers"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
ucode-auth = { workspace = true }
ucode-core = { workspace = true }
reqwest = { version = "0.13.2", features = ["stream", "json"] }
toml = "1.0.6"
bytes = "1.11.1"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
futures-util = { workspace = true }
