[package]
name = "ucode-tools"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
ucode-core = { workspace = true }
ucode-providers = { path = "../ucode-providers" }
ignore = { workspace = true }
regex = { workspace = true }
mpatch = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
