[package]
name = "ucode-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ucode"
path = "src/main.rs"

[dependencies]
ucode-core = { workspace = true }
ucode-auth = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
reqwest = { workspace = true }
open = "5.3.3"

[dev-dependencies]
tempfile.workspace = true
