[package]
name = "ucode-tui"
version.workspace = true
edition.workspace = true

[dependencies]
ratatui = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
tokio = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
unicode-width = { workspace = true }
ucode-core = { version = "0.1.0", path = "../ucode-core" }
pulldown-cmark = { version = "0.13.1", default-features = false }
ucode-auth = { version = "0.1.0", path = "../ucode-auth" }

[dev-dependencies]
tempfile = { workspace = true }
serde_json = { workspace = true }
